src/v2/guide/installation.md
vuejs-vn/vuejs.org pull request #16
Opened 2017-10-04 18:50 UTC by nguyenvanduocit

2017-10-06 18:01 UTC, phanan requested changes

2017-10-06 18:01 UTC, phanan commented on src/v2/guide/installation.md
> +Khi sử dụng Vue, chúng tôi khuyên bạn nên cài [Vue Devtools](https://github.com/vuejs/vue-devtools#vue-devtools) vào trình duyệt, nó cho phép bạn kiểm tra và debug ứng dụng Vue với giao diện thân thi
Anh nghĩ nên tách ra làm hai câu`…vào trình duyệt. Add-on này giúp bạn kiểm tra và debug (kiểm lỗi) ứng dụng Vue với giao diện thân thiện.` thì nghe tự nhiên hơn.

2017-10-06 18:01 UTC, phanan commented on src/v2/guide/installation.md
> +<p class="tip">Đừng sử dụng phiên bản rút gọn khi đang trong quá trình phát triển ứng dụng vì bạn sẽ không thấy cảnh báo về những lỗi thường gặp.</p>
"Khi đang trong quá trình" quá phức tạp. Anh nghĩ nên viết đơn giản là "Trong quá trình phát triển" hoặc đơn giản hơn nữa "Nếu đang phát triển ứng dụng, đừng dùng phiên bản rút gọn vì bạn sẽ không thấy…" Nói chung là nên ngắn gọn, bỏ bớt từ lằng nhằng.

2017-10-06 18:01 UTC, phanan commented on src/v2/guide/installation.md
> +Khuyên dùng: [https://cdn.jsdelivr.net/npm/vue](https://cdn.jsdelivr.net/npm/vue), nó sẽ ánh xạ tới phiên bản mới nhất khi Vue được xuất bản lên npm. Bạn có thể xem mã nguồn của package trên npm tại
"Ánh xạ" là một từ rất khó hiểu. Anh nghĩ "nó sẽ trỏ tới phiên bản mới nhất của Vue trên npm" rõ ràng hơn mà vẫn đủ nghĩa.

2017-10-06 18:01 UTC, phanan commented on src/v2/guide/installation.md
> +Chúng tôi khuyên bạn nên sử dụng NPM khi muốn xây dựng một ứng dụng lớn với Vue. Nó hoạt động rất tốt với các module bundler(các công cụ đóng gói module) như [Webpack](https://webpack.js.org/) hoặc [
`NPM hoạt động rất tốt` thì nghe thuận tai hơn là "Nó." Tiếng Việt mình rất ít khi sử dụng "nó" với ngữ cảnh như tiếng Anh.

2017-10-06 18:01 UTC, phanan commented on src/v2/guide/installation.md
> +<p class="tip">CLI tạo ra các ứng dụng có sử dụng nhiều kiến thức về Node.js và các công cụ hỗ trợ. Nếu bạn mới làm quen với Vue hoặc các công cụ build, chúng tôi đề nghị bạn nên xem qua <a href="./"
`CLI yêu cầu nhiều kiến thức`…

2017-10-06 18:01 UTC, phanan commented on src/v2/guide/installation.md
> +Vue.js cung cấp một CLI giúp nhanh chóng tạo ra khởi đầu cho các ứng dụng đầy tham vọng. Nó cung cấp các cài đặt build của một quy trình hiện đại về frontend. Chỉ tốn vài phút để cài đặt và chạy với
`Vue.js cung cấp một CLI giúp nhanh chóng tạo ra khởi đầu cho các ứng dụng đầy tham vọng` nghe rất kì cục.

2017-10-06 18:01 UTC, phanan commented on src/v2/guide/installation.md
> +Vì bản build chỉ có Runtime nhẹ hơn 30% so với bản đầy đủ, bạn nên sử dụng nó bất cứ khi nào có thể. Nếu bạn vẫn muốn sử dụng bản đầy đủ, bạn cần phải cấu hình một bí danh(alias) trong bundler:
Sao lại viết hoa `Runtime?`

2017-10-06 18:01 UTC, phanan commented on src/v2/guide/installation.md
> +Trong thư mục [`dist/` của package trên NPM](https://cdn.jsdelivr.net/npm/vue/dist/) bạn sẽ thấy nhiều bản build khác nhau của Vue.js. Dưới đây là cái nhìn tổng quát về sự khác biệt giữ chúng:
Typo `giữa`.

2017-10-06 18:01 UTC, phanan commented on src/v2/guide/installation.md
> +Trong thư mục [`dist/` của package trên NPM](https://cdn.jsdelivr.net/npm/vue/dist/) bạn sẽ thấy nhiều bản build khác nhau của Vue.js. Dưới đây là cái nhìn tổng quát về sự khác biệt giữ chúng:
Hoặc chỉ cần nói đơn giản là "Dưới đây là các điểm khác biệt cơ bản giữa các phiên bản này:"

2017-10-06 18:01 UTC, phanan commented on src/v2/guide/installation.md
> +- **Runtime**: đoạn mã có trách nhiệm tạo ra đối tượng Vue, render(kết xuất) và cập nhật virtual DOM, v.v.. Cơ bản là tất cả mọi thứ ngoại trừ compiler.
Thiếu một khoảng trắng giữa `render` và `(kết xuất)`.

2017-10-06 18:01 UTC, phanan commented on src/v2/guide/installation.md
> +Nếu bạn cần biên dịch các template ở phía client (ví dụ như truyền chuỗi vào option `template`, hoặc gắn Vue vào element và sử dụng DOM của nó làm template), bạn sẽ cần compiler, đó là bản build đầy
Thiếu khoảng trắng `đầy đủ(full)`. Ngoài ra dịch `thus` chỗ này sai. Có thể dịch thoát ra thành "bạn sẽ cần trình biên dịch có trong bản build đầy đủ (full):"

2017-10-06 18:01 UTC, phanan commented on src/v2/guide/installation.md
> +Chế độ development/production đã được định sẵn trong các bản build UMD: bản chưa nén(un-minified) có chế độ development, bản đã nén(minified) có chế độ production.
Minify không phải là nén (compress). Anh nghĩ nên giữ nguyên là minify.

2017-10-06 18:01 UTC, phanan commented on src/v2/guide/installation.md
> +Chế độ development/production đã được định sẵn trong các bản build UMD: bản chưa nén(un-minified) có chế độ development, bản đã nén(minified) có chế độ production.
Lưu ý khoảng trắng.

2017-10-06 18:01 UTC, phanan commented on src/v2/guide/installation.md
> +Các bản build CommonJS và ES Module này dựa vào `process.env.NODE_ENV` để xác định chế độ chạy. Bạn nên cấu hình bundler phù hợp để thay thế biến môi trường nhằm điều khiển chế độ chạy vủa Vue. Chế đ
"Chế độ production sẽ cho phép các công cụ nén như UglifyJS loại bỏ các dòng code chỉ dành cho chế độ development một cái triệt để, giúp giảm dung lượng file." Khúc này từ đâu ra?

2017-10-06 18:01 UTC, phanan commented on src/v2/guide/installation.md
> +Sử dụng plugin [DefinePlugin](https://webpack.js.org/plugins/define-plugin/):
Sử dụng DefinePlugin của Webpack.

2017-10-06 18:01 UTC, phanan commented on src/v2/guide/installation.md
> +Đọc thêm [các lời khuyên khi triển khai production](deployment.html).
"khi deploy lên production." Anh không nghĩ "deploy" có thể dịch là "triển kha" trong ngữ cảnh này.

2017-10-06 18:01 UTC, phanan commented on src/v2/guide/installation.md
> +**Quan trọng**: các file đã được build trong thư mục `/dist` trên GitHub chỉ được tạo ra khi release. Nó không chứa các thay đổi mới nhất mà bạn thấy trong các commit, bạn phải tự build nó từ mã nguồ
Cả câu sau có thể dịch ngắn gọn là "Bạn sẽ phải tự build lấy nếu muốn dùng phiên bản từ mã nguồn mới nhất."

2017-10-06 18:01 UTC, phanan commented on src/v2/guide/installation.md
> +Chỉ có bản build UMD khả dụng trong Bower.
"là khả dụng…" mặc dù anh thấy từ "khả dụng" không ổn.

2017-10-06 18:06 UTC, nguyenvanduocit commented on src/v2/guide/installation.md
> +Các bản build CommonJS và ES Module này dựa vào `process.env.NODE_ENV` để xác định chế độ chạy. Bạn nên cấu hình bundler phù hợp để thay thế biến môi trường nhằm điều khiển chế độ chạy vủa Vue. Chế đ
Do em hiểu sao "string literals" rồi. Lúc dịch em coi lại code, nghĩ rằng "string literals" là "production" hoặc "development", nên dịch ra thành vậy. :)

2017-10-06 18:10 UTC, nguyenvanduocit commented on src/v2/guide/installation.md
> +- **Runtime**: đoạn mã có trách nhiệm tạo ra đối tượng Vue, render(kết xuất) và cập nhật virtual DOM, v.v.. Cơ bản là tất cả mọi thứ ngoại trừ compiler.
Em sẽ dùng `render` luôn nhé, vì trong index.md anh có dùng qua rồi.

2017-10-06 18:22 UTC, nguyenvanduocit commented on src/v2/guide/installation.md
> +<a class="button" href="/js/vue.js" download>Phiên bản development</a><span class="light info">Với đầy đủ cảnh báo và chế độ debug</span>
Chữ trong nút này bị rớt dòng, chắc mình nên style lại nó trong PR khác ha anh. @phanan

2017-10-06 18:33 UTC, nguyenvanduocit commented on src/v2/guide/installation.md
> +Vue.js cung cấp một CLI giúp nhanh chóng tạo ra khởi đầu cho các ứng dụng đầy tham vọng. Nó cung cấp các cài đặt build của một quy trình hiện đại về frontend. Chỉ tốn vài phút để cài đặt và chạy với
nghe kỳ thiệt. em dịch lại thành `Vue.js cung cấp một CLI giúp nhanh chóng khởi tạo các ứng dụng Single Page Application mạnh mẽ`

2017-10-07 00:25 UTC, phanan approved these changes

2017-10-07 00:25 UTC, merged