[WIP] src/v2/guide/comparison.md
vuejs-vn/vuejs.org pull request #34
Opened 2017-10-15 11:00 UTC by halink0803

2017-10-15 15:28 UTC, phanan requested changes

2017-10-15 15:28 UTC, phanan commented on src/v2/guide/comparison.md
> +title: So sánh với những frameworks khác
Chúng ta thường không dùng thể số nhiều của tiếng Anh trong tiếng Việt. Ở đây nói "những frameworks" thì cũng như nói "những những framework" ;)

2017-11-13 11:31 UTC, phanan commented
Thật sự bản dịch này đọc lên nghe rất giống Google translate, có nhiều chỗ không thuận tai đối với người Việt.

2017-11-13 12:21 UTC, halink0803 commented
Vâng, em đang để WIP để đọc và chỉnh sửa lại. Nếu để thuận tai em sợ sẽ không sát với ý nghĩa của bài đầu, nhưng em sẽ thử, xong có chỗ nào chưa được anh nhận xét lại nhé.

2017-11-13 12:22 UTC, phanan commented
Em nên dịch thoáng ra, không cần phải bám sát 1:1 (như có nói trong [hướng dẫn dịch](https://github.com/vuejs-vn/vuejs.org#lưu-ý-khi-dịch)).

2018-03-25 15:31 UTC, closed without merging