[WIP] src/v2/examples/elastic-header.md
vuejs-vn/vuejs.org pull request #58
Opened 2017-11-08 18:42 UTC by tungbt94

Translate `src/v2/examples/elastic-header.md` to Vietnamese

2017-11-16 04:29 UTC, nguyenvanduocit requested changes
Cập nhật theo thảo luận trên slack

2017-11-16 04:29 UTC, nguyenvanduocit submitted a review, later dismissed

2017-11-16 04:29 UTC, nguyenvanduocit commented on src/v2/examples/elastic-header.md
> +title: Tiêu đề đàn hồi
Tiêu đề đàn hồi được

2017-11-17 15:58 UTC, phanan approved these changes

2017-11-17 15:59 UTC, merged