[WIP] src/v2/examples/hackernews.md
vuejs-vn/vuejs.org pull request #68
Opened 2018-01-09 08:04 UTC by ttquoccuong

begin translating

2018-01-09 08:21 UTC, ttquoccuong commented
cho em hỏi có ai dịch câu này cho hay và chính xác không mọi người
"CSS extraction for production"

2018-01-09 20:47 UTC, phanan requested changes

2018-01-09 20:47 UTC, phanan commented on src/v2/examples/hackernews.md
> +- Cập nhật danh sách tin trong thời gian thật với hiệu ứng lật (FLIP)
FLIP animation không phải là hiệu ứng lật. Xem thêm: https://aerotwist.com/blog/flip-your-animations/

2018-01-09 20:47 UTC, phanan commented on src/v2/examples/hackernews.md
> +  - Lấy dữ liệu từ Server-side trước khi hiển thị
Từ server, không phải từ server-side. Ngoài ra data prefetching không đơn giản là "lấy dữ liệu trước khi hiển thị" (dữ liệu nào chẳng được lấy trước khi hiển thị?)

2018-01-09 20:47 UTC, phanan commented on src/v2/examples/hackernews.md
> +> Lưu ý: Bản demo này có thể cần một ít thời gian để tải nếu không có ai truy cập nó trong một khoảng thời gian nhất định.
"Spin up time" không phải là "thời gian để tải." Nếu dịch thoáng thì có thể dịch là "…có thể tốn chút ít thời gian để khởi động nếu đã lâu không có ai truy cập."

2018-01-09 20:47 UTC, phanan commented on src/v2/examples/hackernews.md
>    - CSS extraction for production
Nguyên khúc này dịch sót.

2020-09-16 05:50 UTC, namdau commented
Thank you for your contribution but unfortunately we'll gonna archive this repo in favor of the official v3 documentation which is being forked here https://github.com/vuejs-vn/docs-next.

Please help to submit your PR over there from now on.

2020-09-16 07:45 UTC, namdau commented
Close this one in favor of adapting [v3 doc repo ](https://github.com/vuejs-vn/docs-next).

2020-09-16 07:45 UTC, closed without merging