[WIP] src/v2/guide/components-registration.md
vuejs-vn/vuejs.org pull request #78
Opened 2019-02-18 06:14 UTC by cuongtran8

Bản dịch đầu tiên

2019-02-24 14:24 UTC, cuongtran8 commented
@phanan @nguyenvanduocit @tatthien các bạn xem giúp mình bản dịch này với

2019-02-24 19:22 UTC, phanan requested changes
Cảm ơn bạn. Mình có một số đề nghị như trên.

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +Cho tới nay, chúng ta chỉ tạo ra những component sử dụng cú pháp `Vue.component`:
```suggestion
Cho tới nay, chúng ta chỉ mới tạo ra những component sử dụng cú pháp `Vue.component`:
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
>    // ... options ...
```suggestion
  // ... các tùy biến ...
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +Những component này được **đăng kí toàn cục**. Nó có nghĩa rằng component có thể sử dụng trong template của bất cứ root Vue instance (`new Vue`) sau khi được đăng kí. Ví dụ:
```suggestion
Những component này được **đăng kí ở cấp toàn cục**. Điều này có nghĩa là sau khi đăng kí, một component có thể được dùng trong template của bất cứ đối tượng Vue gốc (`new Vue`) nào. Ví dụ:
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +Điều này còn áp dụng cho tất cả những components con, nghĩa là tất cả ba component trên sẽ sẵn sàng để sử dụng _ngay bên trong chúng_.
```suggestion
Điều này còn áp dụng cho tất cả những components con, tức là tất cả ba component trên đều có thể sử dụng _lẫn nhau_.
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +## Đăng kí component cục bộ
```suggestion
## Đăng kí ở cấp cục bộ
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +Việc đăng kí component toàn cục thường không phải là một biện pháp lí tưởng. Ví dụ, nếu bạn sử dụng hệ thống xây dựng hệ thống như Webpack, đăng kí toàn cục cho tất cả các component có nghĩa là kể cả
```suggestion
Đăng kí component toàn cục thường không phải là một biện pháp lí tưởng. Ví dụ, nếu bạn sử dụng một hệ thống xây dựng (build system) như Webpack, đăng kí toàn cục cho tất cả các component có nghĩa là kể cả khi bạn không sử dụng một component nữa, component đó vẫn có thể được thêm vào bản build cuối cùng. Điều này là không cần thiết và làm tăng lượng JavaScript mà người dùng phải tải xuống.
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +Trong những trường hợp này, bạn có thể định nghĩa component như là những JavaScript objects:
```suggestion
Trong những trường hợp này, bạn có thể định nghĩa component dưới dạng object trong JavaScript:
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +Sau khi định nghĩa các component, bạn có thể sử dụng trong tuỳ chọn `components`:
```suggestion
Sau đó khai báo các component bạn muốn dùng trong tuỳ chọn `components`:
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +Cho mỗi thuộc tính trong đối tượng component, key sẽ là tên cuả custom element, trong khi giá trị sẽ bao gồm tuỳ chọn của đối tượng cho component.
```suggestion
Đối với mỗi thuộc tính trong object `components`, khóa (key) sẽ trở thành tên của phần tử tùy biến (custom element), trong khi giá trị (value) sẽ bao gồm object `options` cho component.
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +Chú ý rằng **component được đăng kí cục bộ sẽ _không_ sẵn sàng để sử dụng trong các subcomponents**. Ví dụ, nếu như bạn muốn sử dụng `ComponentA` trong `ComponentB`, bạn phải sử dụng như sau:
```suggestion
Lưu ý rằng **bạn sẽ _không_ truy xuất được đến các component được đăng kí cục bộ từ các component con**. Ví dụ, nếu như bạn muốn sử dụng `ComponentA` trong `ComponentB`, bạn phải khai báo như sau:
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +Hoặc nếu bạn sử dụng ES2015 modules, như là Babel hay Webpack, cú pháp có thể giống như sau:
```suggestion
Hoặc nếu bạn sử dụng module ES2015 (thông qua Babel hay Webpack):
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +Chú ý rằng trong ES2015+, đặt tên biến như `ComponentA` bên trong một object là viết tắt của `ComponentA: ComponentA`, trường hợp này tên của biến đồng thời là:
```suggestion
Chú ý rằng trong ES2015+, đặt một tên biến như `ComponentA` bên trong một object là cách viết tắt của `ComponentA: ComponentA`, trường hợp này tên của biến đồng thời là:
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +- Tên của custom element để sử dụng trong template, và
```suggestion
- tên của đối tượng tùy biến để sử dụng trong template, và
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +- Tên của biến bao gồm các tuỳ chọn của component
```suggestion
- tên của biến bao gồm các tuỳ chọn cho component
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +## Module hệ thống
```suggestion
## Hệ thống module
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +Nếu bạn không sử dụng module systems với `import`/`require`, bạn có thể bỏ qua mục này, nếu bạn có sử dụng thì chúng tôi có một vài hướng dẫn và lời khuyên cho bạn
```suggestion
Nếu không sử dụng hệ thống module với `import`/`require`, bạn có thể bỏ qua mục này. Ngược lại thì chúng tôi có một vài hướng dẫn và lời khuyên cho bạn.
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +### Đăng kí component cục bộ trong Module System
```suggestion
### Đăng kí component cục bộ trong hệ thống module
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +Nếu bạn sử dụng module system, giống như là Babel và Webpack. Trong trường hợp này, chúng tôi khuyến khích tạo ra môt `components`, với mỗi component có một file riêng.
```suggestion
Nếu vẫn còn đọc đến những dòng này thì khả năng cao là bạn đang sử dụng một hệ thống module như Babel và Webpack. Trong trường hợp này, chúng tôi khuyến khích tạo một file riêng cho mỗi component.
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +Và bạn sẽ cần phải import từng component mà bạn muốn sử dụng, trước khi bạn đăng kí cục bộ. Ví dụ, giả thuyết trong file `ComponentB.js` hoặc `ComponentB.vue`:
```suggestion
Và bạn sẽ cần phải nhập (`import`) từng component mà bạn muốn sử dụng trước khi đăng kí cục bộ. Ví dụ, trong một file `ComponentB.js` hoặc `ComponentB.vue`:
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +Cả hai `ComponentA` và `ComponentC` có thể sử dụng trong template của `ComponentB`.
Giờ thì bạn có thể sử dụng cả `ComponentA` và `ComponentC` trong template của `ComponentB`.

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +### Tự động đăng kí toàn cục của những base component
```suggestion
### Tự động đăng kí toàn cục cho component cơ sở
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +Rất nhiều component sẽ được sử dụng chung, có thể chỉ là bao gồm một element như là một input hay một nút. CHúng ta đôi khi gọi chúng nhưng là một [base components](../style-guide/#Base-component-nam
```suggestion
Bạn sẽ có nhiều component dùng chung, ví dụ một component dạng wrapper cho một phần tử như `button` hoặc `input`. Chúng tôi đôi khi gọi những component này là [component cơ sở](../style-guide/#Base-component-names-strongly-recommended) (base component), và những component cơ sở này có khuynh hướng được dùng rất thường xuyên bên trong các component khác.
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +Kết quả là có nhiều component có thể bao gồm một danh sách dài các base components:
```suggestion
Kết quả là nhiều component có thể có một danh sách component cơ sở khá dài:
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +Chỉ để hỗ trợ cho một vài markup trong template:
```suggestion
Chỉ để hỗ trợ cho một chút markup trong template:
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +May thay, nếu bạn đang sử dụng Webpack (hoặc [Vue CLI 3+](https://github.com/vuejs/vue-cli), công cụ sử dụng Webpack), bạn có thể sử dụng `require.context` cho đăng kí toàn cục với những base compone
```suggestion
May thay, sử dụng Webpack (hoặc [Vue CLI 3+](https://github.com/vuejs/vue-cli), công cụ sử dụng Webpack), bạn có thể đăng kí các component cơ sở thông dụng ở cấp toàn cục với `require.context`. Đây là một ví dụ về cách nhúng các component cơ sở ở cấp toàn cục component vào file bắt đầu của ứng dụng (ví dụ: `src/main.js`):
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
>  ```js
Bạn chưa dịch ví dụ này.

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +Nhớ rằng **đăng kí component toàn cục phải sẵn sàng trước khi root Vue instance được tạo ra (with `new Vue`)**. [Đây là ví dụ](https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/sr
```suggestion
Nhớ rằng **bạn phải đăng kí component cấp toàn cục trước khi khởi tạo đối tượng Vue gốc (`new Vue`)**. [Đây là một ví dụ](https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/src/components/_globals.js) trong một ngữ cảnh thực tế.
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +Khi định nghĩa một component với kiểu PascalCase, có thể sử dụng cả hai cách để tạo tham chiếu tới element của nó. Điều này có nghĩa là cả hai cách viết `<my-component-name>` và `<MyComponentName>` đ
```suggestion
Khi định nghĩa một component ở dạng PascalCase, bạn có thể sử dụng cả hai cách khi tham chiếu tới phần tử web của nó. Điều này có nghĩa là cả hai cách viết `<my-component-name>` và `<MyComponentName>` đều được chấp nhận. Tuy nhiên, cần chú ý là chỉ có các tên của component với kebab-case mới sử dụng được trên DOM (nghĩa là các template không phải dạng chuỗi).
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +#### Với kebab-case
```suggestion
#### Dùng kebab-case
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +#### Với PascalCase
```suggestion
#### Dùng PascalCase
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +Vue.component('component-todo', { /* ... */ })
```suggestion
Vue.component('my-component-name', { /* ... */ })
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +Component được đặt tên khi đăng kí. Ví dụ khi đăng kí component toàn cục, ta thường thấy cú pháp:
```suggestion
Component được đặt tên khi đăng kí. Ví dụ khi đăng kí component ở cấp toàn cục, ta thường thấy cú pháp:
```

2019-02-24 19:22 UTC, phanan commented on src/v2/guide/components-registration.md
> +> Nếu như bạn chưa làm quen với component bạn có thể bắt đầu từ [cơ bản về components](components.html).
```suggestion
> Nếu chưa làm quen với component bạn có thể bắt đầu từ phần [Cơ bản về component](components.html).
```

2019-02-25 03:06 UTC, cuongtran8 commented
Xin cảm ơn bạn, mình đã sửa lại một số chỗ như bạn đã góp ý ở trên. Bạn xem lại giúp mình nhé.

2019-02-25 06:15 UTC, phanan commented
👍  nhưng vẫn còn một số điểm góp ý mà bạn chưa resolve.

2019-02-25 06:51 UTC, cuongtran8 commented
> 👍 nhưng vẫn còn một số điểm góp ý mà bạn chưa resolve.

xin lỗi mình đọc lướt không chú ý nên không thấy phần hidden messenger,mình đã sửa lại phần còn thiếu bạn xem giúp nhé, cảm ơn bạn

2019-02-25 09:44 UTC, phanan requested changes

2019-02-25 09:44 UTC, phanan commented on src/v2/guide/components-registration.md
> +  // đường dẫn tới thư mục con (nếu có)
```suggestion
  // có tìm component trong các thư mục con hay không
```

2019-02-25 09:44 UTC, phanan commented on src/v2/guide/components-registration.md
> +  // định nghĩa dùng để tìm những tệp component cơ sở
```suggestion
  // regular expression để tìm các file component cơ sở
```

2019-02-25 09:44 UTC, phanan commented on src/v2/guide/components-registration.md
> +      // Tách phần đầu `'./` và phần mở rộng từ tên của tệp tin
```suggestion
      // Bỏ phần đầu `'./` và đuôi file
```

2019-02-25 09:44 UTC, phanan commented on src/v2/guide/components-registration.md
> +    // Tìm kiếm tuỳ biến của component trong cấu hình mặc định
```suggestion
    // Tìm kiếm các tùy chọn của component trong thuộc tính `.default`
```

2019-02-25 09:44 UTC, phanan commented on src/v2/guide/components-registration.md
> +    // nếu nó được gửi với `export default`, ngược lại module gốc sẽ được sử dụng.
```suggestion
    // Thuộc tính này sẽ khả dụng nếu component sử dụng `export default`
    // nếu không thì dùng chính `componentConfig`
```

2019-02-25 11:03 UTC, cuongtran8 commented
@phanan Đã sửa bạn nhé, cảm ơn bạn nhiều.

2019-02-25 18:50 UTC, phanan approved these changes

2019-02-25 18:50 UTC, merged

2019-02-25 18:51 UTC, phanan commented
👍